// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShaurmaN0App.Data;

#nullable disable

namespace ShaurmaN0App.Migrations
{
    [DbContext(typeof(ShaurmaDbContext))]
    partial class ShaurmaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShaurmaN0App.Models.Menus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("fc8a1dd6-3965-4e85-bc07-8712a4cb12d0"));

                    b.Property<Guid?>("MenusCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MenusCategoryId");

                    b.ToTable("Menus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ddf08b52-554b-4a09-a506-bba06530d019"),
                            Name = "Shaurma",
                            Price = 5.0
                        },
                        new
                        {
                            Id = new Guid("e2063479-b45d-4383-8b08-89f39de3939d"),
                            Name = "Cola",
                            Price = 1.5
                        });
                });

            modelBuilder.Entity("ShaurmaN0App.Models.MenusCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("42e51504-0b8c-4364-8f97-ff3af664febe"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenusCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("14407acd-1405-4683-a9d1-111214c38179"),
                            Name = "dessert"
                        },
                        new
                        {
                            Id = new Guid("a7beddaf-f163-45ec-b5fb-24c3990b0692"),
                            Name = "drinkables"
                        });
                });

            modelBuilder.Entity("ShaurmaN0App.Models.Menus", b =>
                {
                    b.HasOne("ShaurmaN0App.Models.MenusCategory", "MenusCategory")
                        .WithMany()
                        .HasForeignKey("MenusCategoryId");

                    b.Navigation("MenusCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
